In [25]:
import pandas as pd
import numpy as np
import seaborn as sns

In [26]:
df = pd.read_csv('../data/raw/gurgaon_property.csv')

In [27]:
df.head()

,property_name,property_type,society,price,price_per_sq_fit,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Sohna,flat,breez global hill view,0.35,6315.0,554.0,Carpet area: 554.16 (51.48 sq.m.),2,2,2,not_available,"Sohna, Gurgaon, Haryana",14.0,West,0 to 1 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Property is on 14th floor and look towards ara...,[],"['Power Back-up', 'Security / Fire Alarm', 'Li...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Sohna,flat,hcbs sports ville,0.38,5067.0,750.0,Built Up area: 750 (69.68 sq.m.)Carpet area: 6...,2,2,2,not_available,"Sohna, Sohna, Gurgaon, Haryana",9.0,East,undefined,"['The roadside cafe', 'GD Goenka Mess', 'ROyal...",Best in class property available at sohna loca...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'..."
2,2 BHK Flat in Sector 92 Gurgaon,flat,sare crescent parc,0.49,4909.0,998.0,Carpet area: 998 (92.72 sq.m.),2,2,2,not_available,"Sector 92 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","On second floor, east facing bedrooms",NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Amenities3 out of 5'..."
3,2 BHK Flat in Sector 89 Gurgaon,flat,greenopolis,0.80,4820.0,1660.0,Super Built up area 1660(154.22 sq.m.),2,3,3,"study room,others","Sector - 89, Gurgaon, Sector 89 Gurgaon, Gurga...",8.0,NaN,Under Construction,"['Orris Community Center', 'Indian Oil', 'Essa...",Best location flat in 3c greenopolis,[],"['Intercom Facility', 'Lift(s)', 'Swimming Poo...","['Environment4 out of 5', 'Safety4 out of 5', ..."
4,3 BHK Flat in Sector-33 Sohna,flat,godrej nature plus,1.55,9955.0,1557.0,Carpet area: 1557 (144.65 sq.m.),3,2,3+,not_available,"Sector-33 Sohna, Gurgaon, Haryana",8.0,East,Within 6 months,"['Signature Global Infinity Mall Sohna', 'Bads...",The apartment is on a lower floor and is east ...,[],"['Feng Shui / Vaastu Compliant', 'Security / F...",NaN

In [28]:
df['area_type'] = df['areaWithType'].str.extract(
    r'\)\s*(.*)'
)[0]

In [29]:
df['area_type'].value_counts()

area_type
                                                                                    2581
Carpet area: 1161 sq.ft. (107.86 sq.m.)                                               18
Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                15
Carpet area: 1200 sq.ft. (111.48 sq.m.)                                               14
Carpet area: 1500 sq.ft. (139.35 sq.m.)                                               13
                                                                                    ...
Built Up area: 450 sq.ft. (41.81 sq.m.)Carpet area: 425 sq.ft. (39.48 sq.m.)           1
Built Up area: 1950 sq.ft. (181.16 sq.m.)Carpet area: 1750 sq.ft. (162.58 sq.m.)       1
Built Up area: 2200 sq.ft. (204.39 sq.m.)Carpet area: 1850 sq.ft. (171.87 sq.m.)       1
Built Up area: 1575 sq.ft. (146.32 sq.m.)Carpet area: 1435 sq.ft. (133.32 sq.m.)       1
Built Up area: 1760 sq.ft. (163.51 sq.m.)Carpet area: 1670 sq.ft. (155.15 sq.m.)       1
Name: count, Length: 850, dtype: int64

In [30]:
df['area_sqm'] = df['areaWithType'].str.extract(r'\(([\d.]+)\s*sq\.m\.\)')

In [31]:
df['build_up'] = df['area_sqm'].astype(float) * 10.7639

In [32]:
df['area_unit'] = df['areaWithType'].str.extract(
    r'([\d.]+)\s*(sq\.ft\.|sq\.m\.|sq\.yd\.)',
    expand=False
)[1]

In [33]:
df['area_unit'].value_counts()

area_unit
sq.m.    3916
Name: count, dtype: int64

In [34]:
def convert_to_sqft(row):
    value = row['area_value']
    unit = row['area_unit']
    
    if pd.isna(value) or pd.isna(unit):
        return np.nan
    
    if unit == 'sq.ft.':
        return value
    
    elif unit == 'sq.m.':
        return value * 10.7639
    
    elif unit == 'sq.yd.':
        return value * 9
    
    return np.nan

In [35]:
df.shape

(3940, 24)

In [36]:
df.columns

Index(['property_name', 'property_type', 'society', 'price',
       'price_per_sq_fit', 'area', 'areaWithType', 'bedRoom', 'bathroom',
       'balcony', 'additionalRoom', 'address', 'floorNum', 'facing',
       'agePossession', 'nearbyLocations', 'description', 'furnishDetails',
       'features', 'rating', 'area_type', 'area_sqm', 'build_up', 'area_unit'],
      dtype='object')

In [37]:
df.dtypes #type

property_name        object
property_type        object
society              object
price               float64
price_per_sq_fit    float64
area                float64
areaWithType         object
bedRoom               int64
bathroom              int64
balcony              object
additionalRoom       object
address              object
floorNum            float64
facing               object
agePossession        object
nearbyLocations      object
description          object
furnishDetails       object
features             object
rating               object
area_type            object
area_sqm             object
build_up            float64
area_unit            object
dtype: object

In [38]:
df.isnull().sum() # missing values

property_name          0
property_type          0
society              562
price                  0
price_per_sq_fit       0
area                   0
areaWithType           0
bedRoom                0
bathroom               0
balcony                0
additionalRoom         0
address               11
floorNum              20
facing              1170
agePossession          1
nearbyLocations      205
description            0
furnishDetails      1026
features             704
rating               448
area_type             32
area_sqm              32
build_up              32
area_unit             24
dtype: int64

In [39]:
df.duplicated().sum() # this cheak dulicate

np.int64(0)

In [40]:
df.describe()

,price,price_per_sq_fit,area,bedRoom,bathroom,floorNum,build_up
count,3940.000000,3940.000000,3.940000e+03,3940.000000,3940.000000,3920.000000,3.908000e+03
mean,2.475975,13917.687563,4.647793e+03,3.350761,3.395685,6.685459,4.887979e+03
std,2.922788,23183.530425,1.176006e+05,1.993977,2.032369,6.014085,1.407156e+05
min,0.070000,2.000000,4.500000e+01,1.000000,1.000000,0.000000,4.499310e+01
25%,0.900000,6790.000000,1.187000e+03,2.000000,2.000000,2.000000,1.250012e+03
50%,1.500000,9000.000000,1.700000e+03,3.000000,3.000000,4.000000,1.741976e+03
75%,2.657500,13752.000000,2.290000e+03,4.000000,4.000000,10.000000,2.300030e+03
max,31.500000,600000.000000,7.250000e+06,36.000000,36.000000,51.000000,8.711999e+06

In [41]:
df.to_csv('../data/raw/gurgaon_property.csv')